spring:
  application:
    name: inventory-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8082